jupyterhub:
  proxy:
    service:
      type: "ClusterIP"
  hub:
    allowNamedServers: ${ hub_allow_named_servers }
    config:
      Authenticator:
        admin_users:
        - ${ admin_user }
      GitHubOAuthenticator:
        client_id: ${ github_client_id }
        client_secret: ${ github_client_secret }
        oauth_callback_url: ${ github_callback_url }
      JupyterHub:
        admin_access: true
        authenticator_class: github
  singleuser:
    serviceAccountName: "daskhub-sa"
    profileList:
%{for profile in singleuser_profile_list ~}
    - display_name: ${ profile.display_name }
      description: "${ profile.description }"
      default: ${ profile.default }
      kubespawner_override:
        image: ${ profile.kubespawner_override.image }
%{ endfor ~}
    memory:
      guarantee: ${ singleuser_memory_guarantee }
    storage:
      capacity: ${ singleuser_storage_capacity }
      homeMountPath: ${ singleuser_storage_mount_path }
    extraEnv:
      TZ: "America/Chicago"

dask-gateway:
  enabled: false
  gateway:
    auth:
      type: null

dask-kubernetes:
  enabled: true